name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci --force

    - name: Install frontend
      run: cd ./frontend && npm ci

    - name: Install backend
      run: cd ./backend && npm ci

    - name: Start backend server
      run: |
            cd ./backend
            npm run dev &
            disown

    - name: Start frontend server
      run: |
            cd ./frontend
            npm start &
            disown
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test --reporter=list

    - name: Run postman tests
      run: npm run postman

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload newman Report 
      uses: actions/upload-artifact@v3
      if: always()
      with:
          name: newman report
          path: newman/
          retention-days: 30
